MCU = at90usb1286
F_CPU = 16000000
F_USB = $(F_CPU)
ARCH = AVR8
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
BOOTLOADER = halfkay

# PS/2 Mouse
MOUSEKEY_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_USE_USART = yes
